import io
import zipfile
from services.session import get_or_create_session

def generate_scaffold_zip(session_id):
    session = get_or_create_session(session_id, "anonymous")  # We might not have user_id here but session_id is enough to fetch context
    context = session.get("context", {})
    tech_stack = context.get("tech_stack", "Python/Flask").lower()
    project_title = session.get("title", "Project")
    
    memory_file = io.BytesIO()
    with zipfile.ZipFile(memory_file, 'w', zipfile.ZIP_DEFLATED) as zf:
        # Standard README
        readme_content = f"# {project_title}\n\nGenerated by idea2Build.\n\n## Tech Stack\n{context.get('tech_stack', 'Not specified')}\n"
        zf.writestr('README.md', readme_content)
        
        # Determine stack contents
        if "react" in tech_stack and "node" in tech_stack:
            zf.writestr('package.json', '{\n  "name": "starter",\n  "version": "1.0.0",\n  "dependencies": {\n    "react": "^18.2.0",\n    "express": "^4.18.2"\n  }\n}')
            zf.writestr('server.js', 'const express = require("express");\nconst app = express();\n\napp.get("/", (req, res) => res.send("Hello World"));\n\napp.listen(3000, () => console.log("Server ready on port 3000"));')
            zf.writestr('src/App.js', 'import React from "react";\n\nfunction App() {\n  return <div>Hello World</div>;\n}\n\nexport default App;')
        elif "next" in tech_stack:
            zf.writestr('package.json', '{\n  "name": "starter",\n  "version": "1.0.0",\n  "dependencies": {\n    "next": "^14.0.0",\n    "react": "^18.2.0"\n  }\n}')
            zf.writestr('pages/index.js', 'export default function Home() {\n  return <div>Hello World</div>;\n}')
        else: # Default Python/Flask
            zf.writestr('requirements.txt', 'Flask==3.0.0\n')
            zf.writestr('app.py', 'from flask import Flask\napp = Flask(__name__)\n\n@app.route("/")\ndef hello():\n    return "Hello World"\n\nif __name__ == "__main__":\n    app.run(debug=True)')
            
    memory_file.seek(0)
    return memory_file
