import io
import json
import zipfile
from services.session import get_or_create_session


def generate_scaffold_zip(session_id):
    session = get_or_create_session(session_id, "anonymous")
    context = session.get("context", {})
    tech_stack = context.get("tech_stack", "python/flask").lower()
    project_title = session.get("title", "Project")
    idea = context.get("idea_summary", project_title)
    timeline = context.get("timeline", "4 weeks")
    team = context.get("team_size", "solo")

    memory_file = io.BytesIO()
    with zipfile.ZipFile(memory_file, 'w', zipfile.ZIP_DEFLATED) as zf:

        # Always write a solid README
        readme = f"""# {project_title}

> Generated by idea2Build · {idea}

## Project Info
- **Timeline**: {timeline}
- **Team**: {team}
- **Stack**: {context.get('tech_stack', 'See below')}

## Getting Started

"""
        if _is_mern(tech_stack):
            readme += _mern_readme()
            _write_mern(zf, idea)
        elif _is_next(tech_stack):
            readme += _next_readme()
            _write_next(zf, idea)
        elif _is_django(tech_stack):
            readme += _django_readme()
            _write_django(zf, idea)
        elif _is_fastapi(tech_stack):
            readme += _fastapi_readme()
            _write_fastapi(zf, idea)
        else:
            readme += _flask_readme()
            _write_flask(zf, idea)

        readme += f"""
## Project Structure
See folders above.

## Built with idea2Build
https://github.com/your-repo
"""
        zf.writestr("README.md", readme)

    memory_file.seek(0)
    return memory_file


# ── Stack detectors ──────────────────────────────────────

def _is_mern(s): return "mern" in s or ("mongo" in s and "react" in s) or ("node" in s and "react" in s)
def _is_next(s): return "next" in s
def _is_django(s): return "django" in s
def _is_fastapi(s): return "fastapi" in s or "fast api" in s


# ── MERN Stack ───────────────────────────────────────────

def _mern_readme():
    return """```bash
# Backend
cd server && npm install && npm run dev

# Frontend (new terminal)
cd client && npm install && npm start
```
"""

def _write_mern(zf, idea):
    # server/package.json
    zf.writestr("server/package.json", json.dumps({
        "name": "idea2build-server",
        "version": "1.0.0",
        "scripts": {"dev": "nodemon index.js", "start": "node index.js"},
        "dependencies": {
            "express": "^4.18.2",
            "mongoose": "^8.0.0",
            "cors": "^2.8.5",
            "dotenv": "^16.0.3",
            "jsonwebtoken": "^9.0.0",
            "bcryptjs": "^2.4.3"
        },
        "devDependencies": {"nodemon": "^3.0.0"}
    }, indent=2))

    # server/.env.example
    zf.writestr("server/.env.example", """PORT=5000
MONGO_URI=mongodb://localhost:27017/idea2build
JWT_SECRET=your_jwt_secret_here
""")

    # server/index.js
    zf.writestr("server/index.js", f"""const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
require('dotenv').config();

const app = express();
app.use(cors());
app.use(express.json());

// Routes
app.use('/api/auth', require('./routes/auth'));
app.use('/api/user', require('./routes/user'));

app.get('/', (req, res) => res.json({{ message: 'idea2Build API running' }}));

mongoose.connect(process.env.MONGO_URI)
  .then(() => {{
    app.listen(process.env.PORT || 5000, () =>
      console.log(`Server running on port ${{process.env.PORT || 5000}}`));
  }})
  .catch(err => console.error('MongoDB connection error:', err));
""")

    # server/routes/auth.js
    zf.writestr("server/routes/auth.js", """const router = require('express').Router();
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const User = require('../models/User');

// POST /api/auth/register
router.post('/register', async (req, res) => {
  try {
    const { name, email, password } = req.body;
    const existing = await User.findOne({ email });
    if (existing) return res.status(400).json({ error: 'Email already in use' });
    const hashed = await bcrypt.hash(password, 10);
    const user = await User.create({ name, email, password: hashed });
    const token = jwt.sign({ id: user._id }, process.env.JWT_SECRET, { expiresIn: '7d' });
    res.json({ token, user: { id: user._id, name: user.name, email: user.email } });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// POST /api/auth/login
router.post('/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    const user = await User.findOne({ email });
    if (!user) return res.status(400).json({ error: 'Invalid credentials' });
    const match = await bcrypt.compare(password, user.password);
    if (!match) return res.status(400).json({ error: 'Invalid credentials' });
    const token = jwt.sign({ id: user._id }, process.env.JWT_SECRET, { expiresIn: '7d' });
    res.json({ token, user: { id: user._id, name: user.name, email: user.email } });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
""")

    # server/routes/user.js
    zf.writestr("server/routes/user.js", """const router = require('express').Router();
const auth = require('../middleware/auth');
const User = require('../models/User');

router.get('/profile', auth, async (req, res) => {
  try {
    const user = await User.findById(req.user.id).select('-password');
    res.json(user);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
""")

    # server/middleware/auth.js
    zf.writestr("server/middleware/auth.js", """const jwt = require('jsonwebtoken');

module.exports = (req, res, next) => {
  const token = req.header('Authorization')?.replace('Bearer ', '');
  if (!token) return res.status(401).json({ error: 'No token, access denied' });
  try {
    req.user = jwt.verify(token, process.env.JWT_SECRET);
    next();
  } catch {
    res.status(401).json({ error: 'Invalid token' });
  }
};
""")

    # server/models/User.js
    zf.writestr("server/models/User.js", """const mongoose = require('mongoose');

const UserSchema = new mongoose.Schema({
  name: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  password: { type: String, required: true },
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('User', UserSchema);
""")

    # client/package.json
    zf.writestr("client/package.json", json.dumps({
        "name": "idea2build-client",
        "version": "0.1.0",
        "dependencies": {
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "react-router-dom": "^6.8.0",
            "axios": "^1.3.0",
            "react-scripts": "5.0.1"
        },
        "scripts": {
            "start": "react-scripts start",
            "build": "react-scripts build"
        },
        "proxy": "http://localhost:5000"
    }, indent=2))

    # client/src/App.js
    zf.writestr("client/src/App.js", """import React, { useState } from 'react';
import { BrowserRouter as Router, Routes, Route, Navigate } from 'react-router-dom';
import Login from './pages/Login';
import Register from './pages/Register';
import Dashboard from './pages/Dashboard';

function App() {
  const [token, setToken] = useState(localStorage.getItem('token'));

  return (
    <Router>
      <Routes>
        <Route path="/login" element={<Login setToken={setToken} />} />
        <Route path="/register" element={<Register setToken={setToken} />} />
        <Route path="/dashboard" element={token ? <Dashboard /> : <Navigate to="/login" />} />
        <Route path="/" element={<Navigate to={token ? '/dashboard' : '/login'} />} />
      </Routes>
    </Router>
  );
}

export default App;
""")

    # client/src/pages/Login.js
    zf.writestr("client/src/pages/Login.js", """import React, { useState } from 'react';
import axios from 'axios';

export default function Login({ setToken }) {
  const [form, setForm] = useState({ email: '', password: '' });
  const [error, setError] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const res = await axios.post('/api/auth/login', form);
      localStorage.setItem('token', res.data.token);
      setToken(res.data.token);
      window.location.href = '/dashboard';
    } catch (err) {
      setError(err.response?.data?.error || 'Login failed');
    }
  };

  return (
    <div style={{ maxWidth: 400, margin: '100px auto', padding: 24 }}>
      <h2>Login</h2>
      {error && <p style={{ color: 'red' }}>{error}</p>}
      <form onSubmit={handleSubmit}>
        <input placeholder="Email" type="email" value={form.email}
          onChange={e => setForm({...form, email: e.target.value})}
          style={{ display:'block', width:'100%', marginBottom:12, padding:8 }} />
        <input placeholder="Password" type="password" value={form.password}
          onChange={e => setForm({...form, password: e.target.value})}
          style={{ display:'block', width:'100%', marginBottom:12, padding:8 }} />
        <button type="submit" style={{ padding:'8px 24px' }}>Login</button>
      </form>
      <p><a href="/register">Don't have an account? Register</a></p>
    </div>
  );
}
""")

    # client/src/pages/Register.js
    zf.writestr("client/src/pages/Register.js", """import React, { useState } from 'react';
import axios from 'axios';

export default function Register({ setToken }) {
  const [form, setForm] = useState({ name: '', email: '', password: '' });
  const [error, setError] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const res = await axios.post('/api/auth/register', form);
      localStorage.setItem('token', res.data.token);
      setToken(res.data.token);
      window.location.href = '/dashboard';
    } catch (err) {
      setError(err.response?.data?.error || 'Registration failed');
    }
  };

  return (
    <div style={{ maxWidth: 400, margin: '100px auto', padding: 24 }}>
      <h2>Create Account</h2>
      {error && <p style={{ color: 'red' }}>{error}</p>}
      <form onSubmit={handleSubmit}>
        <input placeholder="Name" value={form.name}
          onChange={e => setForm({...form, name: e.target.value})}
          style={{ display:'block', width:'100%', marginBottom:12, padding:8 }} />
        <input placeholder="Email" type="email" value={form.email}
          onChange={e => setForm({...form, email: e.target.value})}
          style={{ display:'block', width:'100%', marginBottom:12, padding:8 }} />
        <input placeholder="Password" type="password" value={form.password}
          onChange={e => setForm({...form, password: e.target.value})}
          style={{ display:'block', width:'100%', marginBottom:12, padding:8 }} />
        <button type="submit" style={{ padding:'8px 24px' }}>Register</button>
      </form>
      <p><a href="/login">Already have an account? Login</a></p>
    </div>
  );
}
""")

    # client/src/pages/Dashboard.js
    zf.writestr("client/src/pages/Dashboard.js", """import React, { useEffect, useState } from 'react';
import axios from 'axios';

export default function Dashboard() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    const token = localStorage.getItem('token');
    axios.get('/api/user/profile', {
      headers: { Authorization: `Bearer ${token}` }
    }).then(res => setUser(res.data))
      .catch(() => { localStorage.removeItem('token'); window.location.href = '/login'; });
  }, []);

  const logout = () => {
    localStorage.removeItem('token');
    window.location.href = '/login';
  };

  return (
    <div style={{ maxWidth: 800, margin: '40px auto', padding: 24 }}>
      <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center' }}>
        <h2>Dashboard</h2>
        <button onClick={logout}>Logout</button>
      </div>
      {user ? (
        <div>
          <p>Welcome, <strong>{user.name}</strong>!</p>
          <p>Email: {user.email}</p>
          {/* Add your main feature components here */}
        </div>
      ) : <p>Loading...</p>}
    </div>
  );
}
""")

    # client/public/index.html
    zf.writestr("client/public/index.html", """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>idea2Build App</title>
</head>
<body>
  <div id="root"></div>
</body>
</html>
""")

    zf.writestr("client/src/index.js", """import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<React.StrictMode><App /></React.StrictMode>);
""")


# ── Flask Stack ──────────────────────────────────────────

def _flask_readme():
    return """```bash
pip install -r requirements.txt
cp .env.example .env
python app.py
```
"""

def _write_flask(zf, idea):
    zf.writestr("requirements.txt", """flask==3.0.0
flask-cors==4.0.0
flask-sqlalchemy==3.1.1
flask-jwt-extended==4.6.0
python-dotenv==1.0.0
bcrypt==4.1.2
""")

    zf.writestr(".env.example", """FLASK_ENV=development
SECRET_KEY=your_secret_key_here
DATABASE_URL=sqlite:///app.db
JWT_SECRET_KEY=your_jwt_secret
""")

    zf.writestr("app.py", """from flask import Flask, jsonify
from flask_cors import CORS
from flask_sqlalchemy import SQLAlchemy
from flask_jwt_extended import JWTManager
from dotenv import load_dotenv
import os

load_dotenv()

app = Flask(__name__)
CORS(app)
app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL', 'sqlite:///app.db')
app.config['JWT_SECRET_KEY'] = os.getenv('JWT_SECRET_KEY', 'dev-secret')
app.config['SECRET_KEY'] = os.getenv('SECRET_KEY', 'dev-secret')

db = SQLAlchemy(app)
jwt = JWTManager(app)

from routes.auth import auth_bp
from routes.user import user_bp
app.register_blueprint(auth_bp)
app.register_blueprint(user_bp)

@app.route('/')
def index():
    return jsonify({'message': 'idea2Build API running'})

if __name__ == '__main__':
    with app.app_context():
        db.create_all()
    app.run(debug=True)
""")

    zf.writestr("models/user.py", """from app import db
from datetime import datetime

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(200), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def to_dict(self):
        return {'id': self.id, 'name': self.name, 'email': self.email}
""")

    zf.writestr("routes/auth.py", """from flask import Blueprint, request, jsonify
from flask_jwt_extended import create_access_token
import bcrypt
from models.user import User
from app import db

auth_bp = Blueprint('auth', __name__, url_prefix='/api/auth')

@auth_bp.route('/register', methods=['POST'])
def register():
    data = request.json
    if User.query.filter_by(email=data['email']).first():
        return jsonify({'error': 'Email already in use'}), 400
    hashed = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt()).decode()
    user = User(name=data['name'], email=data['email'], password=hashed)
    db.session.add(user)
    db.session.commit()
    token = create_access_token(identity=str(user.id))
    return jsonify({'token': token, 'user': user.to_dict()})

@auth_bp.route('/login', methods=['POST'])
def login():
    data = request.json
    user = User.query.filter_by(email=data['email']).first()
    if not user or not bcrypt.checkpw(data['password'].encode(), user.password.encode()):
        return jsonify({'error': 'Invalid credentials'}), 400
    token = create_access_token(identity=str(user.id))
    return jsonify({'token': token, 'user': user.to_dict()})
""")

    zf.writestr("routes/user.py", """from flask import Blueprint, jsonify
from flask_jwt_extended import jwt_required, get_jwt_identity
from models.user import User

user_bp = Blueprint('user', __name__, url_prefix='/api/user')

@user_bp.route('/profile', methods=['GET'])
@jwt_required()
def profile():
    user = User.query.get(get_jwt_identity())
    if not user:
        return jsonify({'error': 'User not found'}), 404
    return jsonify(user.to_dict())
""")


# ── FastAPI Stack ────────────────────────────────────────

def _fastapi_readme():
    return """```bash
pip install -r requirements.txt
cp .env.example .env
uvicorn main:app --reload
```
"""

def _write_fastapi(zf, idea):
    zf.writestr("requirements.txt", """fastapi==0.109.0
uvicorn==0.27.0
sqlalchemy==2.0.25
python-jose[cryptography]==3.3.0
passlib[bcrypt]==1.7.4
python-dotenv==1.0.0
python-multipart==0.0.9
""")

    zf.writestr(".env.example", """SECRET_KEY=your_secret_key_here
DATABASE_URL=sqlite:///./app.db
""")

    zf.writestr("main.py", """from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from database import engine, Base
from routers import auth, user

Base.metadata.create_all(bind=engine)

app = FastAPI(title="idea2Build API")
app.add_middleware(CORSMiddleware, allow_origins=["*"],
    allow_methods=["*"], allow_headers=["*"])

app.include_router(auth.router, prefix="/api/auth", tags=["auth"])
app.include_router(user.router, prefix="/api/user", tags=["user"])

@app.get("/")
def root():
    return {"message": "idea2Build API running"}
""")

    zf.writestr("database.py", """from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import os
from dotenv import load_dotenv
load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./app.db")
engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(bind=engine)
Base = declarative_base()

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
""")


# ── Django Stack ─────────────────────────────────────────

def _django_readme():
    return """```bash
pip install -r requirements.txt
cp .env.example .env
python manage.py migrate
python manage.py runserver
```
"""

def _write_django(zf, idea):
    zf.writestr("requirements.txt", """django==5.0.1
djangorestframework==3.14.0
django-cors-headers==4.3.1
djangorestframework-simplejwt==5.3.1
python-dotenv==1.0.0
""")
    zf.writestr(".env.example", "SECRET_KEY=your_secret_key\nDEBUG=True\n")
    zf.writestr("manage.py", """#!/usr/bin/env python
import os, sys
def main():
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
    from django.core.management import execute_from_command_line
    execute_from_command_line(sys.argv)
if __name__ == '__main__':
    main()
""")


# ── Next.js Stack ────────────────────────────────────────

def _next_readme():
    return """```bash
npm install
npm run dev
```
"""

def _write_next(zf, idea):
    zf.writestr("package.json", json.dumps({
        "name": "idea2build-app",
        "version": "0.1.0",
        "scripts": {"dev": "next dev", "build": "next build", "start": "next start"},
        "dependencies": {
            "next": "^14.0.0",
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "axios": "^1.3.0"
        }
    }, indent=2))
    zf.writestr("pages/index.js", """export default function Home() {
  return <main><h1>idea2Build App</h1><p>Get started by editing pages/index.js</p></main>;
}
""")
    zf.writestr("pages/api/hello.js", """export default function handler(req, res) {
  res.status(200).json({ message: 'idea2Build API running' });
}
""")